spring:
  application:
    name: store

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200
    refreshTokenExpiration: 604800 #7d

  profiles:
    active: dev


springdoc:
  swagger-ui:
    path: "/docs"

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET_KEY}

